name: taswirti
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  flutter_spinkit: ^5.2.0
  image_gallery_saver: ^2.0.3
  cached_network_image: ^3.2.3
  random_string: ^2.3.1
  dio: ^5.2.1+1
  url_launcher: ^6.1.12
  url_launcher_web: ^2.0.0
  google_mobile_ads: ^3.0.0
  firebase_analytics: ^10.4.3
  firebase_core: ^2.14.0
  workmanager: ^0.5.1
  animated_text_kit: ^4.2.2
  animated_size_and_fade: ^3.0.1
  permission_handler: ^10.4.3
  cupertino_icons: ^1.0.5
  fluttertoast: ^8.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
